call plug#begin(expand('~/.vim/plugged'))
Plug 'arcticicestudio/nord-vim'
Plug 'itchyny/lightline.vim'
Plug 'ap/vim-css-color'
Plug 'vimwiki/vimwiki'
Plug 'rust-lang/rust.vim'
call plug#end()
colorscheme nord
set laststatus=2
set noshowmode
set number
let g:lightline = {
      \ 'colorscheme': 'nord',
      \ }
