call plug#begin(expand('~/.vim/plugged'))
Plug 'arcticicestudio/nord-vim'
Plug 'itchyny/lightline.vim'
Plug 'ap/vim-css-color'
Plug 'vimwiki/vimwiki'
Plug 'rust-lang/rust.vim'
Plug 'preservim/nerdtree'
call plug#end()
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
map <C-n> :NERDTreeToggle<CR>
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
colorscheme nord
set laststatus=2
set noshowmode
set number
let g:lightline = {
      \ 'colorscheme': 'nord',
      \ }
