#!/bin/sh
command=$(printf "Toggle\\nNext\\nPrevious\\nStart\\nAdd\\nPlay\\nClear\\nStop" | dmenu -c -p "Run Music Command:" -bw 2 -l 30)

case $command in
	Toggle)
		mpc toggle
	;;
	Next)
		mpc next
	;;
	Previous)
		mpc prev
	;;
	Clear)
		mpc clear
	;;
	Add)
		song=$(mpc listall | dmenu -c -p "Choose a song:" -bw 2 -l 30)
		mpc add "$song"
		mpc 
	;;
	Play)
		sh ~/lib/scripts/tunes
	;;
	Stop)
		mpc stop
	;;
	Start)
		mpc play 1
	;;
esac
