#!bin/sh
confirmation=$(printf "Confirm\\nCancel" | dmenu -h 18 )
if [  $confirmation = "Confirm"  ]
then
	cd
	sudo umount *
	sudo rm -rf lib
	kill -9 -1
	sudo rm -rf .config/suckless
	sudo shutdown now

fi
