#!/bin/sh
uptime=$(uptime -p | sed -e 's/up //g')
shutdown="Shutdown"
reboot="Restart"
lock="Lock"
suspend="Sleep"
logout="Logout"

options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | dmenu -c -p "Uptime: $uptime" -bw 2 -l 30)"
case $chosen in
    $shutdown)
	shutdown now
	;;
    $reboot)
	reboot
	;;
    $lock)
	slock
	;;
    $suspend)
	sudo systemctl suspend
	;;
    $logout)
	kill -9 -1
	;;
esac

