#! /bin/sh

sxhkd -c ~/.config/sxhkd/bsshkdrc &
./.config/polybar/launch.sh &
rm .bash_history

bspc monitor VGA-1 -d 1 2 3 4 5
bspc monitor LVDS-1 -d 6 7 8 9 10


bspc config border_width        3
bspc config window_gap          8

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding          1
bspc config bottom_padding       1
bspc config left_padding         1
bspc config right_padding        1

bspc config active_border_color \#81a1c1
bspc config normal_border_color \#3b4252

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
